### ISSUE TITLE
Not an issue, more like a suggestion, exporting settings

### ISSUE THREAD

**Issue by raphievila** [exeldro/obs-transition-table#13]
Is there's a way I can export the settings to an external text file or JSON, then being able to import it as well?

**Comment by exeldro** [comment]
Can you test if this works for you?
https://github.com/exeldro/obs-transition-table/actions/runs/3554835095

**Comment by raphievila** [comment]
I installed it but I can't find the buttons, I see them in the source code, but not sure where to find them in the UI.







Rafael Vilá

Illustrator, Graphic Designer and Web Developer
Revolution Visual Arts (Owner)



***@***.***

+1 (830) 220-8861
+1 (512) 853-0795
https://revolutionvisualarts.com












---- On Sat, 26 Nov 2022 12:25:32 -0600 Exeldro ***@***.***> wrote ---





Can you test if this works for you?
 https://github.com/exeldro/obs-transition-table/actions/runs/3554835095

**Comment by raphievila** [comment]
---- On Fri, 02 Dec 2022 18:23:47 -0600 Rafael Vila ***@***.***> wrote ---



I installed it but I can't find the buttons, I see them in the source code, but not sure where to find them in the UI.








Rafael Vilá

Illustrator, Graphic Designer and Web Developer
Revolution Visual Arts (Owner)



***@***.***

+1 (830) 220-8861
+1 (512) 853-0795
https://revolutionvisualarts.com












---- On Sat, 26 Nov 2022 12:25:32 -0600 Exeldro ***@***.***> wrote ---













Can you test if this works for you?
 https://github.com/exeldro/obs-transition-table/actions/runs/3554835095

**Comment by exeldro** [comment]
The buttons should be at the bottom center of the transition table dialog.
