### ISSUE TITLE
Please, set 0.2.6 tag

### ISSUE THREAD

**Issue by eribertomota** [exeldro/obs-transition-table#15]
Thanks!

**Comment by eribertomota** [comment]
My suggestion is set this tag before accept my PR #16, to make the GitHub repo compliant with version in OBS Plugins homepage.

I need this tag to update Debian before Feb 05, 2023.

Thank you!

**Comment by exeldro** [comment]
fixed

**Comment by eribertomota** [comment]
Thanks!
