### ISSUE TITLE
Crash on OBS 29.1.3

### ISSUE THREAD

**Issue by GalaxyOfZero** [exeldro/obs-transition-table#22]
I have update my OBS form 29.1.2 to 29.1.3 and the Transition Table Pluging makes my OBS to crash my startup.
[Crash 2023-06-22 17-56-50.txt](https://github.com/exeldro/obs-transition-table/files/11836029/Crash.2023-06-22.17-56-50.txt)

**Comment by exeldro** [comment]
What makes you think Transition Table is causing the crash? The crash report indicates a crash rendering a source. That seems to me not related to Transition Table.

**Comment by GalaxyOfZero** [comment]
i have fix it by myself now
