### ISSUE TITLE
Please, add a tag

### ISSUE THREAD

**Issue by eribertomota** [exeldro/obs-transition-table#3]
I intend to send this plugin to Debian.

Thanks!

**Comment by exeldro** [comment]
0.2.1 tag and release added

**Comment by eribertomota** [comment]
Thanks @exeldro.

I just sent the plugin to Debian. The current status of your plugins is:

1. Already in Debian:
* obs-move-transition
* obs-downstream-keyer

2. Waiting for an initial approval:
* obs-scene-collection-manager
* obs-scene-notes-dock
* obs-transition-table

You can see these packages here[1].

[1] https://qa.debian.org/developer.php?email=eriberto@debian.org

Cheers,

Eriberto
