### ISSUE TITLE
"Any" is not avalaible to translate it

### ISSUE THREAD

**Issue by COOLIGUAY** [exeldro/obs-transition-table#4]
If I add "Any" in es-ES.ini (Any="Cualquiera") to translate it, it's displayed correctly in spanish but doesn't recognize the translated item to work properly.

But if I manually type "Any" in From/To works ok.

![image](https://user-images.githubusercontent.com/55640387/152609144-52fb73fe-a9e4-4997-9ed4-b2dcae786d7a.png)

**Comment by eribertomota** [comment]
Hummm... I arrived now to open a bug about this issue...

**Comment by COOLIGUAY** [comment]
Thank you so much!

With this fix cannot delete a transition that contains "any" in from/to in any language other than english.

![image](https://user-images.githubusercontent.com/55640387/154861964-6412dad9-a2b7-431a-9032-dee316108e35.png)

You cannot delete this line.

No problem if OBS is set to English.

**Comment by exeldro** [comment]
@COOLIGUAY good catch, should be fixed now by https://github.com/exeldro/obs-transition-table/commit/27d3ae802ec7de72499b95c5d0032decb1d80e5e

**Comment by COOLIGUAY** [comment]
Works fine for me, even changing languages.

Awesome work!
