### ISSUE TITLE
5 memory leaks per entry on OBS 27.2

### ISSUE THREAD

**Issue by WizardCM** [exeldro/obs-transition-table#5]
Reproduction steps:

1. Download & install a fresh copy of OBS Studio 27.2.0 (or use the zip version) in portable mode
2. Load then close OBS
3. 0 memory leaks
4. Install the ZIP version of this plugin
5. Load OBS
6. Add an entry - any combination will do it (Any / Any / Cut)
7. Close OBS
8. 5 memory leaks

Log: [2022-02-18 23-20-34.txt](https://github.com/exeldro/obs-transition-table/files/8097054/2022-02-18.23-20-34.txt)

This grows for each entry - I have 42 entries in my scene collection, resulting in 210 memory leaks.

Note - these are cleaned up correctly if an entry is deleted manually (it'll show 0 memory leaks on shutdown), so this is only during shutdown for existing entries.

**Comment by exeldro** [comment]
Fixed and released in version 0.2.3

**Comment by WizardCM** [comment]
Confirmed. Thanks!
