### ISSUE TITLE
Add support for 28.0

### ISSUE THREAD

**Issue by Toniob** [exeldro/obs-transition-table#9]
Hi,

OBS Studio has released its 28.0 beta version. The transition table is not yet compatible with this version, the plugin is disabled on launch, with an error message. Can you please release a new version which works with 28.0 ?

**Comment by exeldro** [comment]
You can download the test version here: https://github.com/exeldro/obs-transition-table/actions/runs/2847777337

**Comment by exeldro** [comment]
Now also signed version:
https://github.com/exeldro/obs-audio-monitor/actions/runs/2924164067
